# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: faa4824b1f57f9d9744989fb4144cee893a9c0ababf8d427fd5181a5b9b779cbda6831f4a3a74a2e00de35fdc5bcef8434ec62077abd8c1a7ee583dd9eaf48a4

test:
  secret_key_base: 7a557db4df195b96b1321a20073557d2513b1656ede8147deb4c522267cb6a05510044d24ab802d47693148dcf2cee92b539f13209076811a75d6e5e643c7606

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
